/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MediaFlowGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Model");
		private final RuleCall cGraphParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Model returns mediaflow::Graph:
		//    Graph
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Graph
		public RuleCall getGraphParserRuleCall() { return cGraphParserRuleCall; }
	}
	public class GraphElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Graph");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGraphKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNodesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNodesNodeParserRuleCall_3_0 = (RuleCall)cNodesAssignment_3.eContents().get(0);
		private final Assignment cEdgesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEdgesEdgeParserRuleCall_4_0 = (RuleCall)cEdgesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Graph returns mediaflow::Graph:
		//    'graph' name=ID '{'
		//        nodes+=Node*
		//        edges+=Edge*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'graph' name=ID '{'
		//    nodes+=Node*
		//    edges+=Edge*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'graph'
		public Keyword getGraphKeyword_0() { return cGraphKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//nodes+=Node*
		public Assignment getNodesAssignment_3() { return cNodesAssignment_3; }
		
		//Node
		public RuleCall getNodesNodeParserRuleCall_3_0() { return cNodesNodeParserRuleCall_3_0; }
		
		//edges+=Edge*
		public Assignment getEdgesAssignment_4() { return cEdgesAssignment_4; }
		
		//Edge
		public RuleCall getEdgesEdgeParserRuleCall_4_0() { return cEdgesEdgeParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class NodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Node");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cResourceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTransformerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Node returns mediaflow::Node:
		//    Resource | Transformer
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Resource | Transformer
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Resource
		public RuleCall getResourceParserRuleCall_0() { return cResourceParserRuleCall_0; }
		
		//Transformer
		public RuleCall getTransformerParserRuleCall_1() { return cTransformerParserRuleCall_1; }
	}
	public class TransformerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Transformer");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cScalerParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTranscoderParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Transformer returns mediaflow::Transformer:
		//    Scaler | Transcoder
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Scaler | Transcoder
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Scaler
		public RuleCall getScalerParserRuleCall_0() { return cScalerParserRuleCall_0; }
		
		//Transcoder
		public RuleCall getTranscoderParserRuleCall_1() { return cTranscoderParserRuleCall_1; }
	}
	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMediaTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMediaTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cMediaTypeMediaTypeEnumRuleCall_5_0 = (RuleCall)cMediaTypeAssignment_5.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cUriKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cEqualsSignKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cUriAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cUriSTRINGTerminalRuleCall_9_0 = (RuleCall)cUriAssignment_9.eContents().get(0);
		private final Keyword cExternalKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cEqualsSignKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cExternalAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cExternalEBooleanParserRuleCall_12_0 = (RuleCall)cExternalAssignment_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cPortsAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cPortsPortParserRuleCall_14_0 = (RuleCall)cPortsAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Resource returns mediaflow::Resource:
		//    'resource' name=ID
		//    '[' 'mediaType' '=' mediaType=MediaType ']'
		//    'uri' '=' uri=STRING
		//    'external' '=' external=EBoolean
		//    '{'
		//        ports+=Port*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'resource' name=ID
		//'[' 'mediaType' '=' mediaType=MediaType ']'
		//'uri' '=' uri=STRING
		//'external' '=' external=EBoolean
		//'{'
		//    ports+=Port*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'resource'
		public Keyword getResourceKeyword_0() { return cResourceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2() { return cLeftSquareBracketKeyword_2; }
		
		//'mediaType'
		public Keyword getMediaTypeKeyword_3() { return cMediaTypeKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//mediaType=MediaType
		public Assignment getMediaTypeAssignment_5() { return cMediaTypeAssignment_5; }
		
		//MediaType
		public RuleCall getMediaTypeMediaTypeEnumRuleCall_5_0() { return cMediaTypeMediaTypeEnumRuleCall_5_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_6() { return cRightSquareBracketKeyword_6; }
		
		//'uri'
		public Keyword getUriKeyword_7() { return cUriKeyword_7; }
		
		//'='
		public Keyword getEqualsSignKeyword_8() { return cEqualsSignKeyword_8; }
		
		//uri=STRING
		public Assignment getUriAssignment_9() { return cUriAssignment_9; }
		
		//STRING
		public RuleCall getUriSTRINGTerminalRuleCall_9_0() { return cUriSTRINGTerminalRuleCall_9_0; }
		
		//'external'
		public Keyword getExternalKeyword_10() { return cExternalKeyword_10; }
		
		//'='
		public Keyword getEqualsSignKeyword_11() { return cEqualsSignKeyword_11; }
		
		//external=EBoolean
		public Assignment getExternalAssignment_12() { return cExternalAssignment_12; }
		
		//EBoolean
		public RuleCall getExternalEBooleanParserRuleCall_12_0() { return cExternalEBooleanParserRuleCall_12_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }
		
		//ports+=Port*
		public Assignment getPortsAssignment_14() { return cPortsAssignment_14; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_14_0() { return cPortsPortParserRuleCall_14_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class ScalerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Scaler");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cScalerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cBackendKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBackendAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBackendBackendEnumRuleCall_4_0 = (RuleCall)cBackendAssignment_4.eContents().get(0);
		private final Keyword cCommandKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCommandAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCommandSTRINGTerminalRuleCall_7_0 = (RuleCall)cCommandAssignment_7.eContents().get(0);
		private final Keyword cReplicasKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cEqualsSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cReplicasAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cReplicasINTTerminalRuleCall_10_0 = (RuleCall)cReplicasAssignment_10.eContents().get(0);
		private final Keyword cWidthKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cEqualsSignKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cWidthAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cWidthINTTerminalRuleCall_13_0 = (RuleCall)cWidthAssignment_13.eContents().get(0);
		private final Keyword cHeightKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cEqualsSignKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cHeightAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cHeightINTTerminalRuleCall_16_0 = (RuleCall)cHeightAssignment_16.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cPortsAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cPortsPortParserRuleCall_18_0 = (RuleCall)cPortsAssignment_18.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//Scaler returns mediaflow::Scaler:
		//    'scaler' name=ID
		//    'backend' '=' backend=Backend
		//    'command' '=' command=STRING
		//    'replicas' '=' replicas=INT
		//    'width' '=' width=INT
		//    'height' '=' height=INT
		//    '{'
		//        ports+=Port*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'scaler' name=ID
		//'backend' '=' backend=Backend
		//'command' '=' command=STRING
		//'replicas' '=' replicas=INT
		//'width' '=' width=INT
		//'height' '=' height=INT
		//'{'
		//    ports+=Port*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'scaler'
		public Keyword getScalerKeyword_0() { return cScalerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'backend'
		public Keyword getBackendKeyword_2() { return cBackendKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//backend=Backend
		public Assignment getBackendAssignment_4() { return cBackendAssignment_4; }
		
		//Backend
		public RuleCall getBackendBackendEnumRuleCall_4_0() { return cBackendBackendEnumRuleCall_4_0; }
		
		//'command'
		public Keyword getCommandKeyword_5() { return cCommandKeyword_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }
		
		//command=STRING
		public Assignment getCommandAssignment_7() { return cCommandAssignment_7; }
		
		//STRING
		public RuleCall getCommandSTRINGTerminalRuleCall_7_0() { return cCommandSTRINGTerminalRuleCall_7_0; }
		
		//'replicas'
		public Keyword getReplicasKeyword_8() { return cReplicasKeyword_8; }
		
		//'='
		public Keyword getEqualsSignKeyword_9() { return cEqualsSignKeyword_9; }
		
		//replicas=INT
		public Assignment getReplicasAssignment_10() { return cReplicasAssignment_10; }
		
		//INT
		public RuleCall getReplicasINTTerminalRuleCall_10_0() { return cReplicasINTTerminalRuleCall_10_0; }
		
		//'width'
		public Keyword getWidthKeyword_11() { return cWidthKeyword_11; }
		
		//'='
		public Keyword getEqualsSignKeyword_12() { return cEqualsSignKeyword_12; }
		
		//width=INT
		public Assignment getWidthAssignment_13() { return cWidthAssignment_13; }
		
		//INT
		public RuleCall getWidthINTTerminalRuleCall_13_0() { return cWidthINTTerminalRuleCall_13_0; }
		
		//'height'
		public Keyword getHeightKeyword_14() { return cHeightKeyword_14; }
		
		//'='
		public Keyword getEqualsSignKeyword_15() { return cEqualsSignKeyword_15; }
		
		//height=INT
		public Assignment getHeightAssignment_16() { return cHeightAssignment_16; }
		
		//INT
		public RuleCall getHeightINTTerminalRuleCall_16_0() { return cHeightINTTerminalRuleCall_16_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_17() { return cLeftCurlyBracketKeyword_17; }
		
		//ports+=Port*
		public Assignment getPortsAssignment_18() { return cPortsAssignment_18; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_18_0() { return cPortsPortParserRuleCall_18_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}
	public class TranscoderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Transcoder");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTranscoderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cBackendKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBackendAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBackendBackendEnumRuleCall_4_0 = (RuleCall)cBackendAssignment_4.eContents().get(0);
		private final Keyword cCommandKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCommandAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCommandSTRINGTerminalRuleCall_7_0 = (RuleCall)cCommandAssignment_7.eContents().get(0);
		private final Keyword cReplicasKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cEqualsSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cReplicasAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cReplicasINTTerminalRuleCall_10_0 = (RuleCall)cReplicasAssignment_10.eContents().get(0);
		private final Keyword cVideoCodecKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cEqualsSignKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cVideoCodecAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cVideoCodecSTRINGTerminalRuleCall_13_0 = (RuleCall)cVideoCodecAssignment_13.eContents().get(0);
		private final Keyword cAudioCodecKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cEqualsSignKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cAudioCodecAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cAudioCodecSTRINGTerminalRuleCall_16_0 = (RuleCall)cAudioCodecAssignment_16.eContents().get(0);
		private final Keyword cContainerKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cEqualsSignKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cContainerAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cContainerSTRINGTerminalRuleCall_19_0 = (RuleCall)cContainerAssignment_19.eContents().get(0);
		private final Keyword cBitrateKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Keyword cEqualsSignKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Assignment cBitrateAssignment_22 = (Assignment)cGroup.eContents().get(22);
		private final RuleCall cBitrateINTTerminalRuleCall_22_0 = (RuleCall)cBitrateAssignment_22.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Assignment cPortsAssignment_24 = (Assignment)cGroup.eContents().get(24);
		private final RuleCall cPortsPortParserRuleCall_24_0 = (RuleCall)cPortsAssignment_24.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_25 = (Keyword)cGroup.eContents().get(25);
		
		//Transcoder returns mediaflow::Transcoder:
		//    'transcoder' name=ID
		//    'backend' '=' backend=Backend
		//    'command' '=' command=STRING
		//    'replicas' '=' replicas=INT
		//    'videoCodec' '=' videoCodec=STRING
		//    'audioCodec' '=' audioCodec=STRING
		//    'container' '=' container=STRING
		//    'bitrate' '=' bitrate=INT
		//    '{'
		//        ports+=Port*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'transcoder' name=ID
		//'backend' '=' backend=Backend
		//'command' '=' command=STRING
		//'replicas' '=' replicas=INT
		//'videoCodec' '=' videoCodec=STRING
		//'audioCodec' '=' audioCodec=STRING
		//'container' '=' container=STRING
		//'bitrate' '=' bitrate=INT
		//'{'
		//    ports+=Port*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'transcoder'
		public Keyword getTranscoderKeyword_0() { return cTranscoderKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'backend'
		public Keyword getBackendKeyword_2() { return cBackendKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//backend=Backend
		public Assignment getBackendAssignment_4() { return cBackendAssignment_4; }
		
		//Backend
		public RuleCall getBackendBackendEnumRuleCall_4_0() { return cBackendBackendEnumRuleCall_4_0; }
		
		//'command'
		public Keyword getCommandKeyword_5() { return cCommandKeyword_5; }
		
		//'='
		public Keyword getEqualsSignKeyword_6() { return cEqualsSignKeyword_6; }
		
		//command=STRING
		public Assignment getCommandAssignment_7() { return cCommandAssignment_7; }
		
		//STRING
		public RuleCall getCommandSTRINGTerminalRuleCall_7_0() { return cCommandSTRINGTerminalRuleCall_7_0; }
		
		//'replicas'
		public Keyword getReplicasKeyword_8() { return cReplicasKeyword_8; }
		
		//'='
		public Keyword getEqualsSignKeyword_9() { return cEqualsSignKeyword_9; }
		
		//replicas=INT
		public Assignment getReplicasAssignment_10() { return cReplicasAssignment_10; }
		
		//INT
		public RuleCall getReplicasINTTerminalRuleCall_10_0() { return cReplicasINTTerminalRuleCall_10_0; }
		
		//'videoCodec'
		public Keyword getVideoCodecKeyword_11() { return cVideoCodecKeyword_11; }
		
		//'='
		public Keyword getEqualsSignKeyword_12() { return cEqualsSignKeyword_12; }
		
		//videoCodec=STRING
		public Assignment getVideoCodecAssignment_13() { return cVideoCodecAssignment_13; }
		
		//STRING
		public RuleCall getVideoCodecSTRINGTerminalRuleCall_13_0() { return cVideoCodecSTRINGTerminalRuleCall_13_0; }
		
		//'audioCodec'
		public Keyword getAudioCodecKeyword_14() { return cAudioCodecKeyword_14; }
		
		//'='
		public Keyword getEqualsSignKeyword_15() { return cEqualsSignKeyword_15; }
		
		//audioCodec=STRING
		public Assignment getAudioCodecAssignment_16() { return cAudioCodecAssignment_16; }
		
		//STRING
		public RuleCall getAudioCodecSTRINGTerminalRuleCall_16_0() { return cAudioCodecSTRINGTerminalRuleCall_16_0; }
		
		//'container'
		public Keyword getContainerKeyword_17() { return cContainerKeyword_17; }
		
		//'='
		public Keyword getEqualsSignKeyword_18() { return cEqualsSignKeyword_18; }
		
		//container=STRING
		public Assignment getContainerAssignment_19() { return cContainerAssignment_19; }
		
		//STRING
		public RuleCall getContainerSTRINGTerminalRuleCall_19_0() { return cContainerSTRINGTerminalRuleCall_19_0; }
		
		//'bitrate'
		public Keyword getBitrateKeyword_20() { return cBitrateKeyword_20; }
		
		//'='
		public Keyword getEqualsSignKeyword_21() { return cEqualsSignKeyword_21; }
		
		//bitrate=INT
		public Assignment getBitrateAssignment_22() { return cBitrateAssignment_22; }
		
		//INT
		public RuleCall getBitrateINTTerminalRuleCall_22_0() { return cBitrateINTTerminalRuleCall_22_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_23() { return cLeftCurlyBracketKeyword_23; }
		
		//ports+=Port*
		public Assignment getPortsAssignment_24() { return cPortsAssignment_24; }
		
		//Port
		public RuleCall getPortsPortParserRuleCall_24_0() { return cPortsPortParserRuleCall_24_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_25() { return cRightCurlyBracketKeyword_25; }
	}
	public class PortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Port");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPortKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDirectionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDirectionDirectionEnumRuleCall_2_0 = (RuleCall)cDirectionAssignment_2.eContents().get(0);
		
		//Port returns mediaflow::Port:
		//    'port' name=ID direction=Direction
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'port' name=ID direction=Direction
		public Group getGroup() { return cGroup; }
		
		//'port'
		public Keyword getPortKeyword_0() { return cPortKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//direction=Direction
		public Assignment getDirectionAssignment_2() { return cDirectionAssignment_2; }
		
		//Direction
		public RuleCall getDirectionDirectionEnumRuleCall_2_0() { return cDirectionDirectionEnumRuleCall_2_0; }
	}
	public class EdgeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Edge");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEdgeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSourceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSourcePortCrossReference_3_0 = (CrossReference)cSourceAssignment_3.eContents().get(0);
		private final RuleCall cSourcePortIDTerminalRuleCall_3_0_1 = (RuleCall)cSourcePortCrossReference_3_0.eContents().get(1);
		private final Keyword cToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTargetAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cTargetPortCrossReference_5_0 = (CrossReference)cTargetAssignment_5.eContents().get(0);
		private final RuleCall cTargetPortIDTerminalRuleCall_5_0_1 = (RuleCall)cTargetPortCrossReference_5_0.eContents().get(1);
		
		//Edge returns mediaflow::Edge:
		//    'edge' name=ID
		//    'from' source=[mediaflow::Port|ID]
		//    'to' target=[mediaflow::Port|ID]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'edge' name=ID
		//'from' source=[mediaflow::Port|ID]
		//'to' target=[mediaflow::Port|ID]
		public Group getGroup() { return cGroup; }
		
		//'edge'
		public Keyword getEdgeKeyword_0() { return cEdgeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'from'
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }
		
		//source=[mediaflow::Port|ID]
		public Assignment getSourceAssignment_3() { return cSourceAssignment_3; }
		
		//[mediaflow::Port|ID]
		public CrossReference getSourcePortCrossReference_3_0() { return cSourcePortCrossReference_3_0; }
		
		//ID
		public RuleCall getSourcePortIDTerminalRuleCall_3_0_1() { return cSourcePortIDTerminalRuleCall_3_0_1; }
		
		//'to'
		public Keyword getToKeyword_4() { return cToKeyword_4; }
		
		//target=[mediaflow::Port|ID]
		public Assignment getTargetAssignment_5() { return cTargetAssignment_5; }
		
		//[mediaflow::Port|ID]
		public CrossReference getTargetPortCrossReference_5_0() { return cTargetPortCrossReference_5_0; }
		
		//ID
		public RuleCall getTargetPortIDTerminalRuleCall_5_0_1() { return cTargetPortIDTerminalRuleCall_5_0_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	public class MediaTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.MediaType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cVIDEOEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cVIDEOVIDEOKeyword_0_0 = (Keyword)cVIDEOEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAUDIOEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAUDIOAUDIOKeyword_1_0 = (Keyword)cAUDIOEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSUBTITLEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSUBTITLESUBTITLEKeyword_2_0 = (Keyword)cSUBTITLEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cIMAGEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cIMAGEIMAGEKeyword_3_0 = (Keyword)cIMAGEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cIMAGE_SEQUENCEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cIMAGE_SEQUENCEIMAGE_SEQUENCEKeyword_4_0 = (Keyword)cIMAGE_SEQUENCEEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum MediaType returns mediaflow::MediaType:
		//    VIDEO='VIDEO' |
		//    AUDIO='AUDIO' |
		//    SUBTITLE='SUBTITLE' |
		//    IMAGE='IMAGE' |
		//    IMAGE_SEQUENCE='IMAGE_SEQUENCE'
		//;
		public EnumRule getRule() { return rule; }
		
		//VIDEO='VIDEO' |
		//AUDIO='AUDIO' |
		//SUBTITLE='SUBTITLE' |
		//IMAGE='IMAGE' |
		//IMAGE_SEQUENCE='IMAGE_SEQUENCE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//VIDEO='VIDEO'
		public EnumLiteralDeclaration getVIDEOEnumLiteralDeclaration_0() { return cVIDEOEnumLiteralDeclaration_0; }
		
		//'VIDEO'
		public Keyword getVIDEOVIDEOKeyword_0_0() { return cVIDEOVIDEOKeyword_0_0; }
		
		//AUDIO='AUDIO'
		public EnumLiteralDeclaration getAUDIOEnumLiteralDeclaration_1() { return cAUDIOEnumLiteralDeclaration_1; }
		
		//'AUDIO'
		public Keyword getAUDIOAUDIOKeyword_1_0() { return cAUDIOAUDIOKeyword_1_0; }
		
		//SUBTITLE='SUBTITLE'
		public EnumLiteralDeclaration getSUBTITLEEnumLiteralDeclaration_2() { return cSUBTITLEEnumLiteralDeclaration_2; }
		
		//'SUBTITLE'
		public Keyword getSUBTITLESUBTITLEKeyword_2_0() { return cSUBTITLESUBTITLEKeyword_2_0; }
		
		//IMAGE='IMAGE'
		public EnumLiteralDeclaration getIMAGEEnumLiteralDeclaration_3() { return cIMAGEEnumLiteralDeclaration_3; }
		
		//'IMAGE'
		public Keyword getIMAGEIMAGEKeyword_3_0() { return cIMAGEIMAGEKeyword_3_0; }
		
		//IMAGE_SEQUENCE='IMAGE_SEQUENCE'
		public EnumLiteralDeclaration getIMAGE_SEQUENCEEnumLiteralDeclaration_4() { return cIMAGE_SEQUENCEEnumLiteralDeclaration_4; }
		
		//'IMAGE_SEQUENCE'
		public Keyword getIMAGE_SEQUENCEIMAGE_SEQUENCEKeyword_4_0() { return cIMAGE_SEQUENCEIMAGE_SEQUENCEKeyword_4_0; }
	}
	public class BackendElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Backend");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFFMPEGEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFFMPEGFFMPEGKeyword_0_0 = (Keyword)cFFMPEGEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGSTREAMEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGSTREAMERGSTREAMERKeyword_1_0 = (Keyword)cGSTREAMEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCUSTOMEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCUSTOMCUSTOMKeyword_2_0 = (Keyword)cCUSTOMEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Backend returns mediaflow::Backend:
		//    FFMPEG='FFMPEG' |
		//    GSTREAMER='GSTREAMER' |
		//    CUSTOM='CUSTOM'
		//;
		public EnumRule getRule() { return rule; }
		
		//FFMPEG='FFMPEG' |
		//GSTREAMER='GSTREAMER' |
		//CUSTOM='CUSTOM'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FFMPEG='FFMPEG'
		public EnumLiteralDeclaration getFFMPEGEnumLiteralDeclaration_0() { return cFFMPEGEnumLiteralDeclaration_0; }
		
		//'FFMPEG'
		public Keyword getFFMPEGFFMPEGKeyword_0_0() { return cFFMPEGFFMPEGKeyword_0_0; }
		
		//GSTREAMER='GSTREAMER'
		public EnumLiteralDeclaration getGSTREAMEREnumLiteralDeclaration_1() { return cGSTREAMEREnumLiteralDeclaration_1; }
		
		//'GSTREAMER'
		public Keyword getGSTREAMERGSTREAMERKeyword_1_0() { return cGSTREAMERGSTREAMERKeyword_1_0; }
		
		//CUSTOM='CUSTOM'
		public EnumLiteralDeclaration getCUSTOMEnumLiteralDeclaration_2() { return cCUSTOMEnumLiteralDeclaration_2; }
		
		//'CUSTOM'
		public Keyword getCUSTOMCUSTOMKeyword_2_0() { return cCUSTOMCUSTOMKeyword_2_0; }
	}
	public class DirectionElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "yohannis.alfa.mediaflow.MediaFlow.Direction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cININKeyword_0_0 = (Keyword)cINEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOUTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOUTOUTKeyword_1_0 = (Keyword)cOUTEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Direction returns mediaflow::Direction:
		//    IN='IN' |
		//    OUT='OUT'
		//;
		public EnumRule getRule() { return rule; }
		
		//IN='IN' |
		//OUT='OUT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IN='IN'
		public EnumLiteralDeclaration getINEnumLiteralDeclaration_0() { return cINEnumLiteralDeclaration_0; }
		
		//'IN'
		public Keyword getININKeyword_0_0() { return cININKeyword_0_0; }
		
		//OUT='OUT'
		public EnumLiteralDeclaration getOUTEnumLiteralDeclaration_1() { return cOUTEnumLiteralDeclaration_1; }
		
		//'OUT'
		public Keyword getOUTOUTKeyword_1_0() { return cOUTOUTKeyword_1_0; }
	}
	
	private final ModelElements pModel;
	private final GraphElements pGraph;
	private final NodeElements pNode;
	private final TransformerElements pTransformer;
	private final ResourceElements pResource;
	private final ScalerElements pScaler;
	private final TranscoderElements pTranscoder;
	private final PortElements pPort;
	private final EdgeElements pEdge;
	private final MediaTypeElements eMediaType;
	private final BackendElements eBackend;
	private final DirectionElements eDirection;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MediaFlowGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pGraph = new GraphElements();
		this.pNode = new NodeElements();
		this.pTransformer = new TransformerElements();
		this.pResource = new ResourceElements();
		this.pScaler = new ScalerElements();
		this.pTranscoder = new TranscoderElements();
		this.pPort = new PortElements();
		this.pEdge = new EdgeElements();
		this.eMediaType = new MediaTypeElements();
		this.eBackend = new BackendElements();
		this.eDirection = new DirectionElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("yohannis.alfa.mediaflow.MediaFlow".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model returns mediaflow::Graph:
	//    Graph
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Graph returns mediaflow::Graph:
	//    'graph' name=ID '{'
	//        nodes+=Node*
	//        edges+=Edge*
	//    '}'
	//;
	public GraphElements getGraphAccess() {
		return pGraph;
	}
	
	public ParserRule getGraphRule() {
		return getGraphAccess().getRule();
	}
	
	//Node returns mediaflow::Node:
	//    Resource | Transformer
	//;
	public NodeElements getNodeAccess() {
		return pNode;
	}
	
	public ParserRule getNodeRule() {
		return getNodeAccess().getRule();
	}
	
	//Transformer returns mediaflow::Transformer:
	//    Scaler | Transcoder
	//;
	public TransformerElements getTransformerAccess() {
		return pTransformer;
	}
	
	public ParserRule getTransformerRule() {
		return getTransformerAccess().getRule();
	}
	
	//Resource returns mediaflow::Resource:
	//    'resource' name=ID
	//    '[' 'mediaType' '=' mediaType=MediaType ']'
	//    'uri' '=' uri=STRING
	//    'external' '=' external=EBoolean
	//    '{'
	//        ports+=Port*
	//    '}'
	//;
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}
	
	//Scaler returns mediaflow::Scaler:
	//    'scaler' name=ID
	//    'backend' '=' backend=Backend
	//    'command' '=' command=STRING
	//    'replicas' '=' replicas=INT
	//    'width' '=' width=INT
	//    'height' '=' height=INT
	//    '{'
	//        ports+=Port*
	//    '}'
	//;
	public ScalerElements getScalerAccess() {
		return pScaler;
	}
	
	public ParserRule getScalerRule() {
		return getScalerAccess().getRule();
	}
	
	//Transcoder returns mediaflow::Transcoder:
	//    'transcoder' name=ID
	//    'backend' '=' backend=Backend
	//    'command' '=' command=STRING
	//    'replicas' '=' replicas=INT
	//    'videoCodec' '=' videoCodec=STRING
	//    'audioCodec' '=' audioCodec=STRING
	//    'container' '=' container=STRING
	//    'bitrate' '=' bitrate=INT
	//    '{'
	//        ports+=Port*
	//    '}'
	//;
	public TranscoderElements getTranscoderAccess() {
		return pTranscoder;
	}
	
	public ParserRule getTranscoderRule() {
		return getTranscoderAccess().getRule();
	}
	
	//Port returns mediaflow::Port:
	//    'port' name=ID direction=Direction
	//;
	public PortElements getPortAccess() {
		return pPort;
	}
	
	public ParserRule getPortRule() {
		return getPortAccess().getRule();
	}
	
	//Edge returns mediaflow::Edge:
	//    'edge' name=ID
	//    'from' source=[mediaflow::Port|ID]
	//    'to' target=[mediaflow::Port|ID]
	//;
	public EdgeElements getEdgeAccess() {
		return pEdge;
	}
	
	public ParserRule getEdgeRule() {
		return getEdgeAccess().getRule();
	}
	
	//enum MediaType returns mediaflow::MediaType:
	//    VIDEO='VIDEO' |
	//    AUDIO='AUDIO' |
	//    SUBTITLE='SUBTITLE' |
	//    IMAGE='IMAGE' |
	//    IMAGE_SEQUENCE='IMAGE_SEQUENCE'
	//;
	public MediaTypeElements getMediaTypeAccess() {
		return eMediaType;
	}
	
	public EnumRule getMediaTypeRule() {
		return getMediaTypeAccess().getRule();
	}
	
	//enum Backend returns mediaflow::Backend:
	//    FFMPEG='FFMPEG' |
	//    GSTREAMER='GSTREAMER' |
	//    CUSTOM='CUSTOM'
	//;
	public BackendElements getBackendAccess() {
		return eBackend;
	}
	
	public EnumRule getBackendRule() {
		return getBackendAccess().getRule();
	}
	
	//enum Direction returns mediaflow::Direction:
	//    IN='IN' |
	//    OUT='OUT'
	//;
	public DirectionElements getDirectionAccess() {
		return eDirection;
	}
	
	public EnumRule getDirectionRule() {
		return getDirectionAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false'
	//;
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
