/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MediaFlowWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMediaFlowWebModule extends DefaultWebModule {

}
