/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.serializer;

import com.google.inject.Inject;
import java.util.Set;
import mediaflow.Edge;
import mediaflow.Graph;
import mediaflow.MediaflowPackage;
import mediaflow.Port;
import mediaflow.Resource;
import mediaflow.Scaler;
import mediaflow.Transcoder;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import yohannis.alfa.mediaflow.services.MediaFlowGrammarAccess;

@SuppressWarnings("all")
public class MediaFlowSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MediaFlowGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MediaflowPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MediaflowPackage.EDGE:
				sequence_Edge(context, (Edge) semanticObject); 
				return; 
			case MediaflowPackage.GRAPH:
				sequence_Graph(context, (Graph) semanticObject); 
				return; 
			case MediaflowPackage.PORT:
				sequence_Port(context, (Port) semanticObject); 
				return; 
			case MediaflowPackage.RESOURCE:
				sequence_Resource(context, (Resource) semanticObject); 
				return; 
			case MediaflowPackage.SCALER:
				sequence_Scaler(context, (Scaler) semanticObject); 
				return; 
			case MediaflowPackage.TRANSCODER:
				sequence_Transcoder(context, (Transcoder) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Edge returns Edge
	 *
	 * Constraint:
	 *     (name=ID source=[Port|ID] target=[Port|ID])
	 * </pre>
	 */
	protected void sequence_Edge(ISerializationContext context, Edge semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MediaflowPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MediaflowPackage.Literals.NAMED_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, MediaflowPackage.Literals.EDGE__SOURCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MediaflowPackage.Literals.EDGE__SOURCE));
			if (transientValues.isValueTransient(semanticObject, MediaflowPackage.Literals.EDGE__TARGET) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MediaflowPackage.Literals.EDGE__TARGET));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEdgeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getEdgeAccess().getSourcePortIDTerminalRuleCall_3_0_1(), semanticObject.eGet(MediaflowPackage.Literals.EDGE__SOURCE, false));
		feeder.accept(grammarAccess.getEdgeAccess().getTargetPortIDTerminalRuleCall_5_0_1(), semanticObject.eGet(MediaflowPackage.Literals.EDGE__TARGET, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Graph
	 *     Graph returns Graph
	 *
	 * Constraint:
	 *     (name=ID nodes+=Node* edges+=Edge*)
	 * </pre>
	 */
	protected void sequence_Graph(ISerializationContext context, Graph semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Port returns Port
	 *
	 * Constraint:
	 *     (name=ID direction=Direction)
	 * </pre>
	 */
	protected void sequence_Port(ISerializationContext context, Port semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MediaflowPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MediaflowPackage.Literals.NAMED_ELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, MediaflowPackage.Literals.PORT__DIRECTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MediaflowPackage.Literals.PORT__DIRECTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPortAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPortAccess().getDirectionDirectionEnumRuleCall_2_0(), semanticObject.getDirection());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns Resource
	 *     Resource returns Resource
	 *
	 * Constraint:
	 *     (name=ID mediaType=MediaType uri=STRING external=EBoolean ports+=Port*)
	 * </pre>
	 */
	protected void sequence_Resource(ISerializationContext context, Resource semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns Scaler
	 *     Transformer returns Scaler
	 *     Scaler returns Scaler
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         backend=Backend 
	 *         command=STRING 
	 *         replicas=INT 
	 *         width=INT 
	 *         height=INT 
	 *         ports+=Port*
	 *     )
	 * </pre>
	 */
	protected void sequence_Scaler(ISerializationContext context, Scaler semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Node returns Transcoder
	 *     Transformer returns Transcoder
	 *     Transcoder returns Transcoder
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         backend=Backend 
	 *         command=STRING 
	 *         replicas=INT 
	 *         videoCodec=STRING 
	 *         audioCodec=STRING 
	 *         container=STRING 
	 *         bitrate=INT 
	 *         ports+=Port*
	 *     )
	 * </pre>
	 */
	protected void sequence_Transcoder(ISerializationContext context, Transcoder semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
