/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MediaFlowUiModule extends AbstractMediaFlowUiModule {

	public MediaFlowUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
