global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "capturer"
    static_configs:
      - targets: ["capturer-session03:9101"]

  - job_name: "broker"
    static_configs:
      - targets: ["broker-session03:9102"]

  - job_name: "transformer"
    static_configs:
      - targets: ["transformer-session03:9103"]

  - job_name: "web_server"
    static_configs:
      - targets: ["web_server-session03:9104"]
