source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               README.md,\
               *.launch,\
               *.sh,\
               input/,\
               validator/
