/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import yohannis.alfa.mediaflow.parser.antlr.internal.InternalMediaFlowParser;
import yohannis.alfa.mediaflow.services.MediaFlowGrammarAccess;

public class MediaFlowParser extends AbstractAntlrParser {

	@Inject
	private MediaFlowGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMediaFlowParser createParser(XtextTokenStream stream) {
		return new InternalMediaFlowParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MediaFlowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MediaFlowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
