/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MediaFlowAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("yohannis/alfa/mediaflow/parser/antlr/internal/InternalMediaFlow.tokens");
	}
}
