/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.ui.tests;

import com.google.inject.Injector;
import mediaflow.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MediaFlowUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("yohannis.alfa.mediaflow.MediaFlow");
	}

}
