/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import yohannis.alfa.mediaflow.ide.contentassist.antlr.internal.InternalMediaFlowParser;
import yohannis.alfa.mediaflow.services.MediaFlowGrammarAccess;

public class MediaFlowParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MediaFlowGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MediaFlowGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNodeAccess().getAlternatives(), "rule__Node__Alternatives");
			builder.put(grammarAccess.getTransformerAccess().getAlternatives(), "rule__Transformer__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getMediaTypeAccess().getAlternatives(), "rule__MediaType__Alternatives");
			builder.put(grammarAccess.getBackendAccess().getAlternatives(), "rule__Backend__Alternatives");
			builder.put(grammarAccess.getDirectionAccess().getAlternatives(), "rule__Direction__Alternatives");
			builder.put(grammarAccess.getGraphAccess().getGroup(), "rule__Graph__Group__0");
			builder.put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
			builder.put(grammarAccess.getScalerAccess().getGroup(), "rule__Scaler__Group__0");
			builder.put(grammarAccess.getTranscoderAccess().getGroup(), "rule__Transcoder__Group__0");
			builder.put(grammarAccess.getPortAccess().getGroup(), "rule__Port__Group__0");
			builder.put(grammarAccess.getEdgeAccess().getGroup(), "rule__Edge__Group__0");
			builder.put(grammarAccess.getGraphAccess().getNameAssignment_1(), "rule__Graph__NameAssignment_1");
			builder.put(grammarAccess.getGraphAccess().getNodesAssignment_3(), "rule__Graph__NodesAssignment_3");
			builder.put(grammarAccess.getGraphAccess().getEdgesAssignment_4(), "rule__Graph__EdgesAssignment_4");
			builder.put(grammarAccess.getResourceAccess().getNameAssignment_1(), "rule__Resource__NameAssignment_1");
			builder.put(grammarAccess.getResourceAccess().getMediaTypeAssignment_5(), "rule__Resource__MediaTypeAssignment_5");
			builder.put(grammarAccess.getResourceAccess().getUriAssignment_9(), "rule__Resource__UriAssignment_9");
			builder.put(grammarAccess.getResourceAccess().getExternalAssignment_12(), "rule__Resource__ExternalAssignment_12");
			builder.put(grammarAccess.getResourceAccess().getPortsAssignment_14(), "rule__Resource__PortsAssignment_14");
			builder.put(grammarAccess.getScalerAccess().getNameAssignment_1(), "rule__Scaler__NameAssignment_1");
			builder.put(grammarAccess.getScalerAccess().getBackendAssignment_4(), "rule__Scaler__BackendAssignment_4");
			builder.put(grammarAccess.getScalerAccess().getCommandAssignment_7(), "rule__Scaler__CommandAssignment_7");
			builder.put(grammarAccess.getScalerAccess().getReplicasAssignment_10(), "rule__Scaler__ReplicasAssignment_10");
			builder.put(grammarAccess.getScalerAccess().getWidthAssignment_13(), "rule__Scaler__WidthAssignment_13");
			builder.put(grammarAccess.getScalerAccess().getHeightAssignment_16(), "rule__Scaler__HeightAssignment_16");
			builder.put(grammarAccess.getScalerAccess().getPortsAssignment_18(), "rule__Scaler__PortsAssignment_18");
			builder.put(grammarAccess.getTranscoderAccess().getNameAssignment_1(), "rule__Transcoder__NameAssignment_1");
			builder.put(grammarAccess.getTranscoderAccess().getBackendAssignment_4(), "rule__Transcoder__BackendAssignment_4");
			builder.put(grammarAccess.getTranscoderAccess().getCommandAssignment_7(), "rule__Transcoder__CommandAssignment_7");
			builder.put(grammarAccess.getTranscoderAccess().getReplicasAssignment_10(), "rule__Transcoder__ReplicasAssignment_10");
			builder.put(grammarAccess.getTranscoderAccess().getVideoCodecAssignment_13(), "rule__Transcoder__VideoCodecAssignment_13");
			builder.put(grammarAccess.getTranscoderAccess().getAudioCodecAssignment_16(), "rule__Transcoder__AudioCodecAssignment_16");
			builder.put(grammarAccess.getTranscoderAccess().getContainerAssignment_19(), "rule__Transcoder__ContainerAssignment_19");
			builder.put(grammarAccess.getTranscoderAccess().getBitrateAssignment_22(), "rule__Transcoder__BitrateAssignment_22");
			builder.put(grammarAccess.getTranscoderAccess().getPortsAssignment_24(), "rule__Transcoder__PortsAssignment_24");
			builder.put(grammarAccess.getPortAccess().getNameAssignment_1(), "rule__Port__NameAssignment_1");
			builder.put(grammarAccess.getPortAccess().getDirectionAssignment_2(), "rule__Port__DirectionAssignment_2");
			builder.put(grammarAccess.getEdgeAccess().getNameAssignment_1(), "rule__Edge__NameAssignment_1");
			builder.put(grammarAccess.getEdgeAccess().getSourceAssignment_3(), "rule__Edge__SourceAssignment_3");
			builder.put(grammarAccess.getEdgeAccess().getTargetAssignment_5(), "rule__Edge__TargetAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MediaFlowGrammarAccess grammarAccess;

	@Override
	protected InternalMediaFlowParser createParser() {
		InternalMediaFlowParser result = new InternalMediaFlowParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MediaFlowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MediaFlowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
