/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.ide;


/**
 * Use this class to register ide components.
 */
public class MediaFlowIdeModule extends AbstractMediaFlowIdeModule {
}
