/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import yohannis.alfa.mediaflow.MediaFlowRuntimeModule;
import yohannis.alfa.mediaflow.MediaFlowStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MediaFlowIdeSetup extends MediaFlowStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MediaFlowRuntimeModule(), new MediaFlowIdeModule()));
	}
	
}
