/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MediaFlowStandaloneSetup extends MediaFlowStandaloneSetupGenerated {

	public static void doSetup() {
		new MediaFlowStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
