/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class MediaFlowWebModule extends AbstractMediaFlowWebModule {
}
