/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMediaFlowScopeProvider extends DelegatingScopeProvider {
}
