/*
 * generated by Xtext 2.40.0
 */
package yohannis.alfa.mediaflow.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import yohannis.alfa.mediaflow.MediaFlowRuntimeModule;
import yohannis.alfa.mediaflow.MediaFlowStandaloneSetup;
import yohannis.alfa.mediaflow.ide.MediaFlowIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class MediaFlowWebSetup extends MediaFlowStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MediaFlowRuntimeModule(), new MediaFlowIdeModule(), new MediaFlowWebModule()));
	}
	
}
